apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.proxies.clusternet.io
spec:
  insecureSkipTLSVerify: true
  group: proxies.clusternet.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: clusternet-hub
    namespace: clusternet-system
  version: v1alpha1

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.federations.clusternet.io
spec:
  insecureSkipTLSVerify: true
  group: federations.clusternet.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: clusternet-hub
    namespace: clusternet-system
  version: v1alpha1
