// +build !ignore_autogenerated

/*
Copyright 2021 The Clusternet Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	url "net/url"

	federations "github.com/clusternet/clusternet/pkg/apis/federations"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*Govern)(nil), (*federations.Govern)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_Govern_To_federations_Govern(a.(*Govern), b.(*federations.Govern), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*federations.Govern)(nil), (*Govern)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_federations_Govern_To_v1alpha1_Govern(a.(*federations.Govern), b.(*Govern), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*url.Values)(nil), (*Govern)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_url_Values_To_v1alpha1_Govern(a.(*url.Values), b.(*Govern), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_Govern_To_federations_Govern(in *Govern, out *federations.Govern, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_Govern_To_federations_Govern is an autogenerated conversion function.
func Convert_v1alpha1_Govern_To_federations_Govern(in *Govern, out *federations.Govern, s conversion.Scope) error {
	return autoConvert_v1alpha1_Govern_To_federations_Govern(in, out, s)
}

func autoConvert_federations_Govern_To_v1alpha1_Govern(in *federations.Govern, out *Govern, s conversion.Scope) error {
	return nil
}

// Convert_federations_Govern_To_v1alpha1_Govern is an autogenerated conversion function.
func Convert_federations_Govern_To_v1alpha1_Govern(in *federations.Govern, out *Govern, s conversion.Scope) error {
	return autoConvert_federations_Govern_To_v1alpha1_Govern(in, out, s)
}

func autoConvert_url_Values_To_v1alpha1_Govern(in *url.Values, out *Govern, s conversion.Scope) error {
	// WARNING: Field TypeMeta does not have json tag, skipping.

	return nil
}

// Convert_url_Values_To_v1alpha1_Govern is an autogenerated conversion function.
func Convert_url_Values_To_v1alpha1_Govern(in *url.Values, out *Govern, s conversion.Scope) error {
	return autoConvert_url_Values_To_v1alpha1_Govern(in, out, s)
}
